[package]
name = "battles"
version = "0.1.0"
authors = ["Sam Kellett <samkellett@gmail.com>"]

[dependencies]
cgmath = "0.12.0"
glium = "0.16.0"
image = "0.12.2"
serde_derive = "0.9.12"
serde = "0.9.12"
toml = "0.3.2"
